---
kind: pipeline
name: pipeline-ci-test

steps:
    - name: helloworld
      image: busybox:latest
      commands:
          - echo 'helloworld'

    - name: preact cli
      image: lowess/preact-cli
      commands:
          - npm install

    - name: slack
      image: plugins/slack
      settings:
          webhook:
              from_secret: slack_webhook
          channel: drone-ci
          link_names: true
          template: >
              {{#success build.status}}
                build {{build.number}} réussi . Un cookie pour @Mathieu Vicot
              {{else}}
                Echec du build {{build.number}} aled 
              {{/success}}
